name: Tests

on: [push, pull_request]

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.0.x, 12.x, 14.0.x, 14.x, 16.0.x, 16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
